import '@/style/globals.scss';
import type { Metadata } from 'next';
import NextAuthProvider from '@/component/common/layout/NextAuthProvider';
import RecoilRootProvider from '@/component/common/layout/RecoilRootProvider';
import ReactQueryProvider from '@/component/common/layout/ReactQueryProvider';
import localFont from 'next/font/local';
import TopBtn from '@/component/common/TopBtn/TopBtn';
import { LuArrowDownToLine } from 'react-icons/lu';

// font
const Strawford = localFont({
  src: [
    {
      path: '../fonts/Strawford/strawfordRegularWebfont.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--Strawford',
  display: 'fallback',
});

export const metadata: Metadata = {
  title: 'thunhye',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // https://bstage.in/?hl=ko
  // https://brm.io/matter-js/demo/#mixed
  // https://bennettfeely.com/clippy/

  // 각 프로젝트 개발, 라이브 서바
  /**
   * backoffice
   * 개발 : 10.10.10.213:3033
   */

  /**
   * 일자리
   * 개발 : http://gnwp.lksmart.co.kr
   * 라이브 : http://job.giba.or.kr
   */

  return (
    <html lang="ko">
      <body className={`${Strawford.variable}`}>
        <NextAuthProvider>
          <RecoilRootProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>

            <TopBtn border="br_round" color="black">
              <LuArrowDownToLine
                role="img"
                aria-label="위로 가기 아이콘"
                style={{
                  transform: 'rotate(180deg)',
                  color: 'var(--white)',
                }}
              />
            </TopBtn>
          </RecoilRootProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
