import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NextAuthProvider from '@/component/layout/NextAuthProvider';
import RecoilRootProvider from '@/component/layout/RecoilRootProvider';
import ReactQueryProvider from '@/component/layout/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <RecoilRootProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </RecoilRootProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
